# Generated by Django 3.2.9 on 2022-01-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20220112_0303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessories',
            old_name='formality',
            new_name='dress_code',
        ),
        migrations.RenameField(
            model_name='outfit',
            old_name='formality',
            new_name='dress_code',
        ),
        migrations.AlterField(
            model_name='outfit',
            name='number_items',
            field=models.IntegerField(verbose_name='Number of items in outfit'),
        ),
    ]
