# Generated by Django 3.2.9 on 2022-01-12 04:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20220112_0332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessories',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='accessories',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Add accessory date'),
            preserve_default=False,
        ),
    ]
