# Generated by Django 3.2.9 on 2022-01-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20220112_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='type',
            field=models.CharField(choices=[('earring', 'earring'), ('necklace', 'necklace'), ('bracelet', 'bracelet'), ('watch', 'watch'), ('hat', 'hat'), ('scarf', 'scarf')], default='earring', max_length=100),
        ),
    ]
