# Generated by Django 3.2.9 on 2022-01-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_accessories_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('dress_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='outfit',
            name='shoes',
            field=models.ManyToManyField(to='main_app.Shoe'),
        ),
    ]
